CREATE TABLE sliderData (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    targetDevice VARCHAR(30) NOT NULL,
    On_off VARCHAR(10),
    slider1 VARCHAR(10),
    slider2 VARCHAR(10),
    reading_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)